### PR TITLE
Use mini-client

### PR DESCRIPTION
**Pull request by feugy**
Replace built-in client with standalone mini-client and mini-service-utils libraries.

This avoid a too tight coupling between a given service and the other services that depend on it.

### CODE REVIEW

**Comment by mcollina** [comment]
Seems good. There is a lot of change here, but no examples. I think having an `examples` folder with both setups would be extremely handy.

**Comment by feugy** [comment]
True. I was waiting for first feedback before adding documentation.
Providing example is even a better idea ! Thx.

**Comment by mcollina** [comment]
@feugy I would want to see how things lays out, rather than guessing :).

**Comment by feugy** [comment]
v2.0.0
- Externalized client using [mini-client][mini-client-url], to decouple clients and service code
- Introduce new terminology, with service descriptor and API groups **[breaking change]**
- Allow to declare API without groups
- Allow to declare API validation in group options
- Force name+version on local client **[breaking change]**
- When parsing exposed APIs, expect 'group' property instead of 'name' **[breaking change]**
- Better documentation and code examples
- More understandable error messages

**Pull request merged**
